// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    'Bx:bxWindowOpen': typeof import('~icons/bx/bx-window-open')['default']
    'Bx:bxWindows': typeof import('~icons/bx/bx-windows')['default']
    'Carbon:checkmarkFilled': typeof import('~icons/carbon/checkmark-filled')['default']
    'Carbon:checkmarkOutline': typeof import('~icons/carbon/checkmark-outline')['default']
    'Carbon:clean': typeof import('~icons/carbon/clean')['default']
    'Carbon:close': typeof import('~icons/carbon/close')['default']
    'Carbon:download': typeof import('~icons/carbon/download')['default']
    'Carbon:earthAmericasFilled': typeof import('~icons/carbon/earth-americas-filled')['default']
    'Carbon:email': typeof import('~icons/carbon/email')['default']
    'Carbon:keyboard': typeof import('~icons/carbon/keyboard')['default']
    'Carbon:language': typeof import('~icons/carbon/language')['default']
    'Carbon:moon': typeof import('~icons/carbon/moon')['default']
    'Carbon:search': typeof import('~icons/carbon/search')['default']
    'Carbon:strawberry': typeof import('~icons/carbon/strawberry')['default']
    'Carbon:sun': typeof import('~icons/carbon/sun')['default']
    'HeroiconsOutline:externalLink': typeof import('~icons/heroicons-outline/external-link')['default']
    'Logos:brave': typeof import('~icons/logos/brave')['default']
    'Logos:chrome': typeof import('~icons/logos/chrome')['default']
    'Logos:microsoftEdge': typeof import('~icons/logos/microsoft-edge')['default']
    'Mdi:contentCopy': typeof import('~icons/mdi/content-copy')['default']
    'Mdi:deleteSweepOutline': typeof import('~icons/mdi/delete-sweep-outline')['default']
    'Mdi:github': typeof import('~icons/mdi/github')['default']
    'Mdi:googleChrome': typeof import('~icons/mdi/google-chrome')['default']
    'Mdi:group': typeof import('~icons/mdi/group')['default']
    'Mdi:heartOutline': typeof import('~icons/mdi/heart-outline')['default']
    'Mdi:microsoftEdge': typeof import('~icons/mdi/microsoft-edge')['default']
    'Mdi:openInNew': typeof import('~icons/mdi/open-in-new')['default']
    'Mdi:shareVariantOutline': typeof import('~icons/mdi/share-variant-outline')['default']
    'Mdi:telegram': typeof import('~icons/mdi/telegram')['default']
    'Mdi:twitter': typeof import('~icons/mdi/twitter')['default']
    'Mdi:ungroup': typeof import('~icons/mdi/ungroup')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    'Tabler:discount2': typeof import('~icons/tabler/discount2')['default']
  }
}
