// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    'Bx:bxWindowOpen': typeof import('~icons/bx/bx-window-open')['default']
    'Bx:bxWindows': typeof import('~icons/bx/bx-windows')['default']
    'Carbon:download': typeof import('~icons/carbon/download')['default']
    'Carbon:email': typeof import('~icons/carbon/email')['default']
    'Carbon:keyboard': typeof import('~icons/carbon/keyboard')['default']
    'Carbon:language': typeof import('~icons/carbon/language')['default']
    'Carbon:logoGithub': typeof import('~icons/carbon/logo-github')['default']
    'Carbon:logoTwitter': typeof import('~icons/carbon/logo-twitter')['default']
    'Carbon:moon': typeof import('~icons/carbon/moon')['default']
    'Carbon:strawberry': typeof import('~icons/carbon/strawberry')['default']
    'Carbon:sun': typeof import('~icons/carbon/sun')['default']
    'HeroiconsOutline:externalLink': typeof import('~icons/heroicons-outline/external-link')['default']
    'Mdi:contentCopy': typeof import('~icons/mdi/content-copy')['default']
    'Mdi:group': typeof import('~icons/mdi/group')['default']
    'Mdi:openInNew': typeof import('~icons/mdi/open-in-new')['default']
    'Mdi:ungroup': typeof import('~icons/mdi/ungroup')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
